stages:
  - test
  - test-coverage
  - deploy

unit_tests:
  stage: test
  tags: [ climate-action ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == 'push'
  image:
    name: ghcr.io/astral-sh/uv:0.8-debian
  variables:
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    UV_CACHE_DIR: .uv-cache
    UV_LINK_MODE: copy
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - $PRE_COMMIT_HOME
      - UV_CACHE_DIR
  before_script:
    - uv sync --locked --all-groups
  script:
    - uv run pre-commit run --all-files
    - uv run pytest -m "not external" --cov --cov-report term --cov-report xml:coverage.xml
    - uv cache prune --ci
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml

test_coverage_threshold:
  stage: test-coverage
  dependencies:
    - unit_tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == 'push'
  image:
    name: python:3.11.5
  before_script:
    - apt-get update && apt-get install -y bc
  script:
    - coverage="$(grep -oP '<coverage[^>]+line-rate="\K[0-9.]+' "coverage.xml")"
    - if (( $(echo "$coverage < 0.8" | bc -l) )); then
        echo "Code coverage is only $(echo "$coverage*100" | bc)%. We recommend a minimum of 80%." && exit 1;
      else
        exit 0;
      fi
  allow_failure:
    exit_codes:
      - 1

optional_linting:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  image:
    name: ghcr.io/astral-sh/uv:0.8-debian
  variables:
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - $PRE_COMMIT_HOME
      - .venv
  before_script:
    - uv add pre-commit
  script:
    - uv run pre-commit run -c .pre-commit-config-optional-linting.yaml --all-files
  allow_failure:
    exit_codes:
      - 1

docker_build_deploy_development:
  stage: deploy
  tags: [ k8s ]
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == 'push'
  image: docker.io/docker:cli
  before_script:
    - echo ${CI_DOCKER_TOKEN} | docker --config ~/ca_config login ${REGISTRY_URL} -u ${CI_DOCKER_USER} --password-stdin
    - docker --config ~/ca_config buildx create --use --name=kube --driver remote tcp://amd64-buildkit-service.ci-cd.svc:1234
  script:
    - |
      docker --config ~/ca_config \
        buildx build \
        --builder=kube \
        --build-arg "CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}" \
        --cache-from=type=registry,ref=${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:buildcache \
        --cache-to=type=registry,ref=${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:buildcache,mode=max \
        --tag ${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:devel \
        --tag ${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:staging \
        --push \
        .

docker_build_deploy_release:
  stage: deploy
  tags: [ k8s ]
  rules:
    - if: $CI_COMMIT_TAG
  image: docker.io/docker:cli
  before_script:
    - echo ${CI_DOCKER_TOKEN} | docker --config ~/ca_config login ${REGISTRY_URL} -u ${CI_DOCKER_USER} --password-stdin
    - docker --config ~/ca_config buildx create --use --name=kube --driver remote tcp://amd64-buildkit-service.ci-cd.svc:1234
  script:
    - |
      docker --config ~/ca_config \
        buildx build \
        --builder=kube \
        --platform=linux/amd64 \
        --tag ${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} \
        --push \
        .
