unit_tests:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  image:
    name: condaforge/mambaforge:23.1.0-4
  variables:
    CONDA_PKGS_DIRS: "$CI_PROJECT_DIR/.conda-pkgs-cache/"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - $PRE_COMMIT_HOME
      - $CONDA_PKGS_DIRS/*.conda
      - $CONDA_PKGS_DIRS/*.tar.bz2
      - $CONDA_PKGS_DIRS/urls*
      - $CONDA_PKGS_DIRS/cache
      - $PIP_CACHE_DIR
  before_script:
    - mamba env create -f environment_cpu.yaml -v
    - mamba init bash
    - source ~/.bashrc
  script:
    - conda run -n ca-lulc-utility-ci pre-commit run --all-files
    - conda run -n ca-lulc-utility-ci pytest -m "not external" --ignore=$CONDA_PKGS_DIRS .

docker_build_deploy_development:
  stage: deploy
  tags: [ k8s ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # temp: delete before merging
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == 'push'
  image: docker.io/docker:cli
  before_script:
    - echo ${CI_DOCKER_TOKEN} | docker --config ~/ca_config login ${REGISTRY_URL} -u ${CI_DOCKER_USER} --password-stdin
    - docker --config ~/ca_config buildx create --use --name=kube --driver remote tcp://amd64-buildkit-service.ci-cd.svc:1234
  script:
    - |
      docker --config ~/ca_config \
        buildx build \
        --builder=kube \
        --build-arg "CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}" \
        --cache-from=type=registry,ref=${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:buildcache \
        --cache-to=type=registry,ref=${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:buildcache,mode=max \
        --tag ${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:devel \
        --tag ${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:staging \
        --push \
        .

docker_build_deploy_release:
  stage: deploy
  tags: [ k8s ]
  rules:
    - if: $CI_COMMIT_TAG
  image: docker.io/docker:cli
  before_script:
    - echo ${CI_DOCKER_TOKEN} | docker --config ~/ca_config login ${REGISTRY_URL} -u ${CI_DOCKER_USER} --password-stdin
    - docker --config ~/ca_config buildx create --use --name=kube --driver remote tcp://amd64-buildkit-service.ci-cd.svc:1234
  script:
    - |
      docker --config ~/ca_config \
        buildx build \
        --builder=kube \
        --platform=linux/amd64 \
        --tag ${REGISTRY_URL}/${GROUP_NAME}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} \
        --push \
        .
