name: ca-lulc-utility
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.14.3
  - geos=3.11.1
  - geotiff=1.7.1
  - httpx=0.24.1
  - mkl=2024.0.0
  - lightning=2.1.4
  - numpy=1.25.0
  - nvidia::cudatoolkit=11.7
  - pandas=2.2.2
  - pillow=9.4.0
  - pip=23.1.2
  - pre-commit=3.6.0
  - pydantic=2.6.2
  - pytest=7.4.2
  - python=3.11.4
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.7
  - requests=2.29.0
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - setuptools=67.8.0
  - shapely=2.0.1
  - torchvision=0.15.2
  - urllib3=1.26.19
  - yaml=0.2.5
  - pip:
      - accelerate==0.20.3
      - albumentations==1.3.1
      - cachetools==5.3.1
      - contextily==1.3.0
      - coolname==2.2.0
      - fastapi==0.100.0
      - geocube==0.4.2
      - geojson==3.0.1
      - huggingface-hub==0.16.4
      - hydra-core==1.3.2
      - neptune==1.10.4
      - ohsome==0.3.2
      - omegaconf==2.3.0
      - onnx==1.14.0
      - onnxruntime==1.15.1
      - pynvml==11.5.0
      - pyjoules==0.5.1
      - rasterio==1.3.8
      - safetensors==0.3.1
      - sentencepiece==0.1.99
      - sentinelhub==3.9.1
      - tifffile==2023.7.10
      - tqdm==4.65.0
      - transformers==4.30.2
      - uvicorn==0.22.0
