name: ca-lulc-utility-deploy
channels:
  - conda-forge
  - defaults
dependencies:
  - httpx=0.24.1
  - numpy=1.25.0
  - pandas=2.2.2
  - pillow=9.4.0
  - pip=23.1.2
  - pydantic=2.6.2
  - python=3.11.4
  - scipy=1.11.1
  - setuptools=67.8.0
  - yaml=0.2.5
  - urllib3=2.2.2
  - pip:
      - cachetools==5.3.1
      - fastapi==0.100.0
      - geocube==0.4.2
      - hydra-core==1.3.2
      - matplotlib==3.7.3
      - neptune==1.10.4
      - ohsome==0.3.2
      - omegaconf==2.3.0
      - onnx==1.14.0
      - onnxruntime==1.15.1
      - rasterio==1.3.8
      - sentinelhub==3.9.1
      - tifffile==2023.7.10
      - tqdm==4.65.0
      - uvicorn==0.22.0
