name: ca-lulc-utility
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - httpx=0.24.1
  - lightning=2.0.5
  - numpy=1.25.0
  - pandas=2.0.3
  - pillow=9.4.0
  - pip=23.1.2
  - python=3.11.4
  - pytorch=2.0.1
  - cpuonly
  - setuptools=67.8.0
  - torchvision=0.15.2
  - pip:
      - cachetools==5.3.1
      - fastapi==0.100.0
      - hydra-core==1.3.2
      - neptune==1.4.0
      - ohsome==0.2.0
      - omegaconf==2.3.0
      - onnx==1.14.0
      - onnxruntime==1.15.1
      - rasterio==1.3.8
      - sentinelhub==3.9.1
      - tifffile==2023.7.10
      - transformers==4.30.2
      - tqdm==4.65.0
      - uvicorn==0.22.0