# @package serve.app

# Model serving API host
host: localhost
port: 8000

mlflow_registry:
  model_name: LULC
  # Served model version, e.g. 1.0.0 or latest.
  # If none it will be automatically resolved to latest released version.
  model_version: ${oc.env:MODEL_VERSION,latest}

# Number of predictions stored in an ephemeral cache.
# Used as an idempotency mechanism.
predict_cache_size: 256

# Version of the app REST API
api_version: v1

# Distance in meters used to increase the processed AOI before inputting it to the inference process
# Used to overcome models' edge prediction issues.
edge_smoothing_buffer: 200