# Model serving API host
host: localhost

# Model serving API host
port: 8000

# Served model version, e.g. CA-LULC-21
# If none it will be automatically resolved to latest, production model
model_version:

# Number of predictions stored in an ephemeral cache.
# Used as an idempotency mechanism.
predict_cache_size: 256

# Version of the app REST API
api_version: v1