defaults:
  - _self_
  - logging

  # Training configuration (from this folder, include the following files)
  - train/soil_sealing/v1:
    - area_descriptor
    - data
    - imagery
    - model
    - label

  # App (inference) configuration  (from this folder, include the following files)
  - serve:
    - app
    - data
    - imagery
    - label

# Directory where all intermediate data is being stored
cache:
  dir: ./cache
  apply: False

mlflow_registry:
  tracking_uri: https://gitlab.heigit.org/api/v4/projects/750/ml/mlflow/

# Extra (generic) training config
environment:
  # Set to run the training process in a deterministic fashion:
  # - https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html
  # - https://lightning.ai/docs/pytorch/stable/common/trainer.html#reproducibility
  deterministic: False

  # Set to run the training process with a profiler attached: https://pytorch-lightning.readthedocs.io/en/1.5.10/advanced/profiler.html
  profiler:

  # Set to log estimated energy consumption of the training process: https://pyjoules.readthedocs.io/en/latest/
  energy_tracker: True

hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
