defaults:
  - _self_
  - data: baseline
  - model: baseline
  - serve: local

cache:
  dir: ./cache



hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

neptune:
  project: ${oc.env:NEPTUNE_PROJECT_ID}
  api_token: ${oc.env:NEPTUNE_PROJECT_API_TOKEN}
  mode: ${oc.env:NEPTUNE_MODE}
  model:
    key: LULC

sentinel_hub:
  api:
    id: ${oc.env:SENTINELHUB_API_ID}
    secret: ${oc.env:SENTINELHUB_API_SECRET}


