defaults:
  - _self_
  - data: baseline
  - model: baseline
  - serve: local
  - imagery: sentinel_hub

cache:
  dir: ./cache

environment:
  deterministic: False
  profiler:
  energy_tracker: True

hydra:
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

neptune:
  project: ${oc.env:NEPTUNE_PROJECT_ID}
  api_token: ${oc.env:NEPTUNE_PROJECT_API_TOKEN}
  mode: ${oc.env:NEPTUNE_MODE}
  model:
    key: LULC
