num_channels: 9
variant: MiT-b0
max_epochs: -1
lr: 0.0005
batch_size: 4
matmul_precision: high
workers: 1
max_image_samples: 3
log_every_n_steps: 10
gradient_clip_val: 0.5
early_stopping:
  patience: 5
augment:
  horizontal_flip:
    p: 0.25
  vertical_flip:
    p: 0.25
  elastic_transform:
    p: 0.25
  coarse_dropout:
    p: 0.25
    max_holes: 15

# Enable determining the optimal batch size and learning rate.
enable_tuning: False
